#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# clear rprompt
setopt transient_rprompt

# peco history
function peco-history() {
  typeset tac
  if which tac > /dev/null; then
    tac=tac
  else
    tac='tail -r'
  fi
  BUFFER=$(fc -l -n 1 | eval $tac | peco --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle redisplay
}
zle -N peco-history
bindkey '^r' peco-history

function peco-src() {
  local selected_dir=$(ghq list -p | peco --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
    zle clear-screen
  else
    zle redisplay
  fi
}
zle -N peco-src
bindkey '^s' peco-src

# Java
alias javac='javac -J-Dfile.encoding=UTF-8'
alias java='java -Dfile.encoding=UTF-8'

# Docker Toolbox (No Docker for Mac)
# eval "$(docker-machine env default)"

# Golang
export GOPATH=$HOME
export GO111MODULE=on

# man color prezto/modules/environment
export LESS_TERMCAP_md=$(tput setaf 4)      # section title: blue.
export LESS_TERMCAP_us=$(tput setaf 3)      # parameters: yellow.

# -N: Nihongo, -C: color by LS_COLORS
alias tree='tree -NC'

# disable autocorrect
alias code='nocorrect code'

# tab stop
tabs -4

# CLI improved
# https://remysharp.com/2018/08/23/cli-improved
alias cat='bat'

# ls to exa, (https://the.exa.website/)
# and fix ls aliases in prezto/modules/utility/init.zsh
alias ls='exa --time-style=iso'
alias l='ls -1a'          # in one column, hidden files.
alias ll='ls -l'          # in long view.
alias lT='ll -T'          # in long tree view.
alias lr='ll -R'          # in long view, recursively.
alias la='ll -a'          # in long view, hidden files.
alias lm='la | "$PAGER"'  # in long view, hidden files through pager.
alias lx='ll -h -s=ext'       # sorted by extension.
alias lk='ll -h -s=size'      # sorted by size, largest last.
alias lt='ll -h -umU -s=mod'  # sorted by modified date, most recent last.
alias lc='lt -h -umU -s=cr'   # sorted by created(changed) date, most recent last.
alias lu='lt -h -umU -s=acc'  # sorted by accessed date, most recent last.
alias sl='ls'             # I often screw this up.
