#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# clear rprompt
setopt transient_rprompt

# peco history
function peco-history() {
  typeset tac
  if which tac > /dev/null; then
    tac=tac
  else
    tac='tail -r'
  fi
  BUFFER=$(fc -l -n 1 | eval $tac | peco --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle redisplay
}
zle -N peco-history
bindkey '^r' peco-history

function peco-src() {
  local selected_dir=$(ghq list -p | peco --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
    zle clear-screen
  else
    zle redisplay
  fi
}
zle -N peco-src
bindkey '^s' peco-src

# Java
alias javac='javac -J-Dfile.encoding=UTF-8'
alias java='java -Dfile.encoding=UTF-8'

# Docker Toolbox (No Docker for Mac)
# eval "$(docker-machine env default)"

# Golang
export GOPATH=$HOME

# LESS search highlight
export LESS_TERMCAP_so=$'\E[01;32;03;40m'

# -N: Nihongo, -C: color by LS_COLORS
alias tree='tree -NC'
